### ISSUE TITLE
In resource helper components, load new resource when `resource` prop changes

### ISSUE THREAD

**Issue by dyyylan** [uptrend-tech/uptrend-redux-modules#37]
Currently we have a situation where a user could change a route param, e.g. `/user/1` to `/user/2`, and if the component tree above `ResourceDetailLoader` remains the same, it would cause the component to not unmount.

When using the `loadOnMount` prop, the resource would not be reloaded when the resource changes, since the component would remain mounted.

We should add a mechanism to load a new resource when the `resource` prop changes, without needing to trigger it manually, either through a new prop (e.g. `loadOnResourceChange`) or just watching for existing prop changes if `loadOnMount` is true.
- [x] Add `componentWillReceiveProps` lifecycle that checks `nextProps.resource` and triggers resource request if `autoLoad` is true.
- [x] Rename `loadOnMount` to `autoLoadResource`
- [x] Also check for change to `nextProps.resourceId` in cWRP lifecycle

**Comment by orther** [comment]
To prevent potential loops it's important we initially use `componentDidMount` lifecycle to request resource on mount BUT use `componentWillRecieveProps` to check `nextProps.resource` to trigger another resource request when for example a route change happens.

Since we no longer are just loading on mount and now load on prop change too, I think it makes sense to rename the `loadOnMount` prop to something more generic like `autoLoadResource`.

**Comment by orther** [comment]
Closed by #38

**Comment by orther** [comment]
Rather than use `componentWillRecieveProps` I opted to use the new React 16 lifecycles as the react team suggests. You can see here: 2030caf
